simulation:
  update_time: 1.
  profile_level: 2
  updates_per_second: 480
  filling:
    layers_per_update: 2
  penetration:
    update_time: 0.05
  broadphase: "axis"
  threads: 1

box:
  diameter: 1.2
  height: 0.7
  wall_thickness: 0.01

probe:
  velocity: -.1
  radius: 0.07
  mass: 1000.

pressure:
  value: 100000
  plate_thickness: 0.05

regolith:
  # physics properties
  restitution: 0.01
  friction: 0.99
  rollingFriction: 1.

  # radii in m
  maxRadius: 0.04
  minRadius: 0.035

  # Below values in kg/m^3

  # Calculated assuming water density 997
  # 2.68*997
  materialDensity: 2672

  maxDensity: 1667
  minDensity: 1364
