simulation:
  big_step: 0.05
  profile_level: 2
  small_steps_per_second: 120
  initialization:
    v2_thershold: 0.005
    squishing_factor: 1.00
    save_file: grains.txt
    #from_file: grains.txt
  pressure:
    plate_v_thershold: 0.08
  penetration:
    big_step: 0.05
  solver:
    iterations: 200
    max_error_ratio: .5
  gravity: -10.
  broadphase: "axis"
  threads: 8
  units_per_m: 100.

box:
  diameter: 1.2
  height: 0.7
  wall_thickness: 0.01

probe:
  velocity: -.1
  radius: 0.035
  mass: 500.
  friction: 1.
  restitution: 0.3

pressure:
  value: 60000
  plate_thickness: 0.1

regolith:
  units_per_m: 100.
  # physics properties
  restitution: 0.3
  friction: 0.35
  rollingFriction: 1.

  # radii in m
  maxRadius: 0.04
  minRadius: 0.03
  # Below values in kg/m^3

  # Calculated assuming water density 997
  # 2.68*997
  materialDensity: 2672

  maxDensity: 1667
  minDensity: 1364
